### ISSUE TITLE
Can you add a suggested uninterruptible power supply in the hardware list?

### ISSUE THREAD

**Issue by lestephane** [getumbrel/umbrel-website#27]
It's my understanding that anyone using Umbrel with open lightning channels needs to ensure the box is running at all times. This means protecting it against power surges and power interruptions. And also, it is my understanding that the RPI is very sensitive to sudden changes in power supply. Why not suggest a UPS for the benefit of umbrel users, so they don't have to research which one will fulfill the requirements of the RPI. And I mean by that the cheapest that is fit for purpose, as tested by existing Umbrel users. Thanks

**Comment by lestephane** [comment]
Relevant discussion https://github.com/rootzoll/raspiblitz/issues/263#issue-397855893

**Comment by lestephane** [comment]
Also relevant: https://github.com/Czino/ring-of-fire, which explains what to do if you use a UPS without shutdown signal.

**Comment by jonsyu** [comment]
Closing this as it's on our radar, looking at a few commercially available options and getting some recommendations from the community.
