### ISSUE TITLE
Create Blog for better engagement

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-website#7]
Create Blog  (maybe **/blog**) for better engagement/traffic so the site should not be just a registration page. 

Types of articles:

* General development / bitcoin topics
* Tips for running a full node from experts
* How to guides on running nodes on different hardware / architecture, or migrating data across.

**Comment by mayankchhabra** [comment]
Can you please move this to https://github.com/orgs/getumbrel/projects/2

**Comment by nolim1t** [comment]
How haha
